/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as DashboardSupplyRouteImport } from './routes/dashboard.supply'
import { Route as DashboardStatusRouteImport } from './routes/dashboard.status'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardLocationRouteImport } from './routes/dashboard.location'
import { Route as DashboardDemandRouteImport } from './routes/dashboard.demand'
import { Route as AdminSupplyRouteImport } from './routes/admin.supply'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRequestsRouteImport } from './routes/admin.requests'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminDemandRouteImport } from './routes/admin.demand'
import { Route as AdminConflictRouteImport } from './routes/admin.conflict'
import { Route as AdminAllocationRouteImport } from './routes/admin.allocation'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardSupplyRoute = DashboardSupplyRouteImport.update({
  id: '/supply',
  path: '/supply',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStatusRoute = DashboardStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLocationRoute = DashboardLocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDemandRoute = DashboardDemandRouteImport.update({
  id: '/demand',
  path: '/demand',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminSupplyRoute = AdminSupplyRouteImport.update({
  id: '/supply',
  path: '/supply',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDemandRoute = AdminDemandRouteImport.update({
  id: '/demand',
  path: '/demand',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConflictRoute = AdminConflictRouteImport.update({
  id: '/conflict',
  path: '/conflict',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAllocationRoute = AdminAllocationRouteImport.update({
  id: '/allocation',
  path: '/allocation',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/admin/allocation': typeof AdminAllocationRoute
  '/admin/conflict': typeof AdminConflictRoute
  '/admin/demand': typeof AdminDemandRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/supply': typeof AdminSupplyRoute
  '/dashboard/demand': typeof DashboardDemandRoute
  '/dashboard/location': typeof DashboardLocationRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/status': typeof DashboardStatusRoute
  '/dashboard/supply': typeof DashboardSupplyRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/admin/allocation': typeof AdminAllocationRoute
  '/admin/conflict': typeof AdminConflictRoute
  '/admin/demand': typeof AdminDemandRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/supply': typeof AdminSupplyRoute
  '/dashboard/demand': typeof DashboardDemandRoute
  '/dashboard/location': typeof DashboardLocationRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/status': typeof DashboardStatusRoute
  '/dashboard/supply': typeof DashboardSupplyRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/admin/allocation': typeof AdminAllocationRoute
  '/admin/conflict': typeof AdminConflictRoute
  '/admin/demand': typeof AdminDemandRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/supply': typeof AdminSupplyRoute
  '/dashboard/demand': typeof DashboardDemandRoute
  '/dashboard/location': typeof DashboardLocationRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/status': typeof DashboardStatusRoute
  '/dashboard/supply': typeof DashboardSupplyRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/services'
    | '/signup'
    | '/admin/allocation'
    | '/admin/conflict'
    | '/admin/demand'
    | '/admin/logs'
    | '/admin/requests'
    | '/admin/settings'
    | '/admin/supply'
    | '/dashboard/demand'
    | '/dashboard/location'
    | '/dashboard/notifications'
    | '/dashboard/settings'
    | '/dashboard/status'
    | '/dashboard/supply'
    | '/admin/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/services'
    | '/signup'
    | '/admin/allocation'
    | '/admin/conflict'
    | '/admin/demand'
    | '/admin/logs'
    | '/admin/requests'
    | '/admin/settings'
    | '/admin/supply'
    | '/dashboard/demand'
    | '/dashboard/location'
    | '/dashboard/notifications'
    | '/dashboard/settings'
    | '/dashboard/status'
    | '/dashboard/supply'
    | '/admin'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/services'
    | '/signup'
    | '/admin/allocation'
    | '/admin/conflict'
    | '/admin/demand'
    | '/admin/logs'
    | '/admin/requests'
    | '/admin/settings'
    | '/admin/supply'
    | '/dashboard/demand'
    | '/dashboard/location'
    | '/dashboard/notifications'
    | '/dashboard/settings'
    | '/dashboard/status'
    | '/dashboard/supply'
    | '/admin/'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  ServicesRoute: typeof ServicesRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/supply': {
      id: '/dashboard/supply'
      path: '/supply'
      fullPath: '/dashboard/supply'
      preLoaderRoute: typeof DashboardSupplyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/status': {
      id: '/dashboard/status'
      path: '/status'
      fullPath: '/dashboard/status'
      preLoaderRoute: typeof DashboardStatusRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/location': {
      id: '/dashboard/location'
      path: '/location'
      fullPath: '/dashboard/location'
      preLoaderRoute: typeof DashboardLocationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/demand': {
      id: '/dashboard/demand'
      path: '/demand'
      fullPath: '/dashboard/demand'
      preLoaderRoute: typeof DashboardDemandRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/supply': {
      id: '/admin/supply'
      path: '/supply'
      fullPath: '/admin/supply'
      preLoaderRoute: typeof AdminSupplyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/demand': {
      id: '/admin/demand'
      path: '/demand'
      fullPath: '/admin/demand'
      preLoaderRoute: typeof AdminDemandRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conflict': {
      id: '/admin/conflict'
      path: '/conflict'
      fullPath: '/admin/conflict'
      preLoaderRoute: typeof AdminConflictRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/allocation': {
      id: '/admin/allocation'
      path: '/allocation'
      fullPath: '/admin/allocation'
      preLoaderRoute: typeof AdminAllocationRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAllocationRoute: typeof AdminAllocationRoute
  AdminConflictRoute: typeof AdminConflictRoute
  AdminDemandRoute: typeof AdminDemandRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupplyRoute: typeof AdminSupplyRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAllocationRoute: AdminAllocationRoute,
  AdminConflictRoute: AdminConflictRoute,
  AdminDemandRoute: AdminDemandRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupplyRoute: AdminSupplyRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardDemandRoute: typeof DashboardDemandRoute
  DashboardLocationRoute: typeof DashboardLocationRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardStatusRoute: typeof DashboardStatusRoute
  DashboardSupplyRoute: typeof DashboardSupplyRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDemandRoute: DashboardDemandRoute,
  DashboardLocationRoute: DashboardLocationRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardStatusRoute: DashboardStatusRoute,
  DashboardSupplyRoute: DashboardSupplyRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  ServicesRoute: ServicesRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
